#Here are some options about particles
Particles:
  #if you disable this, no matter what you but below^^
  enable: true
  default_particle: FLAME
  #10 of these particles spawn at the same time
  number: 10
  #They respawn all 5 ticks by default
  respawn_ticks: 5
  #The radius of spawning
  radius: 0.3
  #The speed of particles. A low speed is more smooth and good-looking. A speed of 1 is just insane.
  speed: 0.05
#time is in minutes
default_reset_time: 10
#each item has a percentage of chance to spawn in a chest
default_item_chance: 100
#I think you know what it is:
UseHologram: true
#remove the chests if the player empty them (they still respawn and everything)
RemoveEmptyChests: true
#removes the chest when a player closes it, even if there's still items in it
RemoveChestAfterFirstOpenning: false

#you can edit or disable all these broadcast messages
respawn_notify:
  natural_respawn:
    enabled: true
    message: "&6The chest &b[Chest] &6has just respawned at [x], [y], [z]!"
  respawn_with_command:
    enabled: true
    message: "&6The chest &b[Chest] &6has just respawned at [x], [y], [z]!"
  respawn_all_with_command:
    enabled: true
    message: "&6All chests where forced to respawn! Get them guys!" 


