name: LootChest
main: fr.black_eyes.lootchest.Main
version: 1.0
api-version: 1.13
description: >
             Plugin for Regenerating Chests
commands:
  lootchest:
    description: Main Command
    aliases: lc